### ISSUE TITLE
graphql-auth examples have issues with permissions

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma-examples#1376]
For example, when you create a new user and use their token to create a new post that you immediately want to punlish afterwards, you get a `Not authorised` error although this should work. This currently happens both in the JS and TS version of the example.

**Comment by createvo** [comment]
I tried but I don't receive that behaviour of `Not authorised` error, either in TS and JS.

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
