### ISSUE TITLE
GraphQL examples: Add computed values to differentiate domain and database models

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-examples#14]
In most cases your domain model and database model is not a 1:1 mapping but includes some computed/derived values which are implemented using "custom resolvers". To make this distinction clearer, we should add a few computed values to the domain model for the GraphQL examples.

**Comment by notrab** [comment]
Happy to take this one @schickling if you have any commonly asked suggestions for these.

I can think right now of a formatted price resolver that returns price (+ currency) stored.

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
