### ISSUE TITLE
Ignore and remove generated nexus files

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma-examples#1424]
The following directory looks like generated code:

https://github.com/prisma/prisma-examples/tree/prisma2/typescript/graphql/src/generated

We should ignore that using a .gitignore file and remove the folder from git unless we have a reason to commit this to VCS.

**Comment by nikolasburk** [comment]
I don't have a super strong opinion on this, but here are a few thoughts why I think it's useful to keep the files:

- `schema.graphql` is a helpful file for people to see at a glance what the GraphQL schema of the example looks like (they don't even need to download an example but can already see this on GitHub). IMO an SDL- version of the GraphQL schema generally belongs into VCS.
- Regarding the typings, I agree more. However, I still think that it's valuable for people to be able to get an overview of this already on GitHub and not having to download everything if they want to see what's going on.

I'm generally in favor of keeping the generated files (also note that the examples have more instructive/educational value rather than showing how to work in production setups). Nonetheless, I'd also be curious to hear @jasonkuhrt's and @Weakky's opinions on whether they think it's best practice to include or not include these generated files.

**Comment by steebchen** [comment]
I see your point and the ad, but I think that generated code should not be committed into VCS, because it messes up git (diffs, PRs, commit sizes, it's easy to get generated files out of sync etc.). @prisma/client is also not committed into VCS, so I think neither should generated nexus files. I think we may even have the same generated code like @prisma/client, so we could generate code to @nexus/client.

**Comment by jasonkuhrt** [comment]
From a framework perspective the generated typings are invisible. We will have a mode in the framework for generating the SDL and some teams will commit it so that PRs can use the diff to as declaratively as possible see the API diff. I also don’t have a strong opinion for these examples. They sit under the framework so users might want the maximum verbose details  here anyways, low level people etc. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nikolasburk** [comment]
> I see your point, but I think that generated code should not be committed into VCS, because it messes up git (diffs, PRs, commit sizes, it's easy to get generated files out of sync etc.).

I generally agree but I think in the context of the examples the size is manageable and the educational value IMO _slightly_ overweighs the problems. So, I'd opt for just keeping them (if we decide to at some point generate the typings into `node_modules/@nexus` then we of course remove the files). Agree?

**Comment by jasonkuhrt** [comment]
@nikolasburk Is your vision to keep `@nexus/schema` examples? I think we should remove all but one once we feel `nexus` the framework is ready enough to be a replacement.

**Comment by nikolasburk** [comment]
Good question, we'll definitely add Nexus examples of the new Nexus. I think it _might_ still be useful for people to see examples of just `@nexus/schema` with Prisma as well, but not sure, could also be confusing for folks who now aren't sure which one to use and what the difference is...

**Comment by steebchen** [comment]
@nikolasburk I'd like to re-visit this. While your intention is good and I agree with your reasoning, the reality is different. Since we often change things in Prisma or Nexus, it often affects generated code. If you clone the example now and generate locally again, you'll see quite a difference in the latest generated code. So either we'll need to automate this using CI, or I still suggest that we remove the generated code; I don't think it's a good idea to commit generated code but then leaving it unsynced.

**Comment by nikolasburk** [comment]
> I don't think it's a good idea to commit generated code but then leaving it unsynced.

That's a fair point! _Ideally_ I'd love to automate this via CI indeed but I guess this is too much effort right now?! 

However, I'd propose to still keep the generated GraphQL schema in VCS and just ignore the generated typings. For that, let's adjust the path to which the files are generated:

```ts
outputs: {
  schema: __dirname + '/schema.graphql',
  typegen: __dirname + '/generated/nexus.ts',
},
```

I think that feels a little bit odd as well, but I do want to keep the GraphQL schema in VCS so people can see at a glance what's going on.

**Comment by nikolasburk** [comment]
Adjusted via: https://github.com/prisma/prisma-examples/commit/dace5858e050977737ef3879e3404c78427581d1

**Comment by nikolasburk** [comment]
Just for completeness, I just stumbled accross this in the[ Nexus docs](https://nexus.js.org/docs/getting-started):

![image](https://user-images.githubusercontent.com/4058327/75548323-4f60e600-5a2d-11ea-87c6-9a0134d5b19f.png)
