### ISSUE TITLE
Add user rules and permissions to typescript/graphql-nextjs

### ISSUE THREAD

**Issue by cr101** [prisma/prisma-examples#1604]
Please add example that shows how to check that a user has the permission to create/delete a post.

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
