### ISSUE TITLE
Test/demo scripts should clean up after themselves

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-examples#1657]
`typescript/script` for examples has a `npm run dev` command that does not clean up after itself, you can only run it once and then need to manually clean up the database (e.g. by manually opening the database and deleting the data or reverting all changes to the file).

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
