### ISSUE TITLE
Firebase functions example app

### ISSUE THREAD

**Issue by shigurenimo** [prisma/prisma-examples#1738]
I want a sample project using FIrebase functions and TypeScript and nexus/schema

**Comment by reiwa** [comment]
I made a sample project for Firebase functions and I tried to use output property of generator to upload prisma/client to Cloud Functions but I don't know how to compile this library.

```
generator client {
  provider      = "prisma-client-js"
  output        = "../functions/_generated/client"
}
```

When I deploy a directory I get this error message because prisma client library genereated contains `query-engine-darwin` and JS file.

```
You most likely forgot to initialize the Prisma Client. Please run `prisma2 generate` and try to run it again
```

**Comment by tylim88** [comment]
facing same issue here, any solution?

**Comment by tylim88** [comment]
i use yarn instead of npm, able to get rid of the error

face unable to connect database error instead, i think this has to do with the public address, but this is another story(https://github.com/prisma/prisma/issues/525#issuecomment-730514332)

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
