### ISSUE TITLE
Make the last step of evolving clearer

### ISSUE THREAD

**Issue by judehunter** [prisma/prisma-examples#1745]
For graphql projects, I did not understand how I should get the `schema.ts` graphql nexus file.
Should I write it by hand? Can I generate it from `schema.prisma`? It's unclear.

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale. 

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
