### ISSUE TITLE
Can I please update example to nexus 0.20.0?

### ISSUE THREAD

**Issue by gustawdaniel** [prisma/prisma-examples#1751]
> typescript/graphql

https://github.com/prisma/prisma-examples/blob/master/typescript/graphql/package.json

https://developer.aliyun.com/mirror/npm/package/nexus/v/0.20.0

**Comment by gustawdaniel** [comment]
Docs of migration:

https://www.nexusjs.org/#/getting-started/migrate-from-nexus-schema

**Comment by janpio** [comment]
Yes please @gustawdaniel, that would be amazin if you could create a PR for that example. 

There are possible other ones still using `nexus-prisma` instead of `nexus-plugin-prisma` as they should (https://github.com/prisma/prisma-examples/search?q=nexus-prisma&unscoped_q=nexus-prisma) - so upgrading those as well should be simple when you tackle the first one.

**Comment by ruheni** [comment]
👋🏽

We've updated the GraphQL examples to the latest versions of the packages and none of them are currently using either `nexus-prisma` or `nexus-plugin-prisma`. Feel free to reopen the issue if you're still running into issues. 🙂
