### ISSUE TITLE
Cannot clone graphql-apollo-server example

### ISSUE THREAD

**Issue by Erzsebet113** [prisma/prisma-examples#1785]
Cannot clone via git clone command due to:

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Is your github still ok?

**Comment by janpio** [comment]
What command did you execute?

**Comment by Erzsebet113** [comment]
git clone git@github.com:prisma/prisma-examples.git --depth=1

This one, according to readme file

**Comment by nikolasburk** [comment]
Hey @Erzsebet113 👋 were you able to sort this out? Since you're the first user reporting an issue like this, I'd guess this might have to do with your local Git/ssh setup. Alternatively you can try to clone via HTTPS:

```
git clone https://github.com/prisma/prisma-examples.git
```

If that still doesn't work, you can download the entire repo as a zipped folder as a workaround 🙂 

![image](https://user-images.githubusercontent.com/4058327/88365944-e5542f00-cd87-11ea-890b-26c55fb73513.png)


I'm closing this issue for now, feel free to ping us again if you need any further help! 🙏
