### ISSUE TITLE
index.d.ts does not reload in VS Code

### ISSUE THREAD

**Issue by TomasMoskala** [prisma/prisma-examples#1793]
Hi, 
if I change field name in server.ts it is not recognized until I manually open index.d.ts.

I changed id in 

```ts
async function post(call: any, callback: any) {
  const { id } = call.request
  const post = await prisma.post.findOne({
    where: {
      id,
    },
  })
  callback(null, post)
}
```

did `npx prisma generate` and updated proto file and underlying db field.
Still have to manually open `index.d.ts`. 
When updating db this is annoying, you don't know where is the bug...

**Comment by nikolasburk** [comment]
Hey @TomasMoskala, thanks a lot for raising this! I think this issue is similar to the issues described [here](https://github.com/prisma/prisma/issues/2962) and [here](https://github.com/prisma/prisma/issues/2771). You can follow those issues to see when the problem is resolved.

As a workaround, you can [restart the TypeScript server inside of VS Code](https://github.com/prisma/prisma/issues/2771#issuecomment-655366309) for the time being.
