### ISSUE TITLE
Add Digital Ocean deployment guide

### ISSUE THREAD

**Issue by darrylyoung** [prisma/prisma-examples#1821]
Hi, everyone. 👋 

To go with the Google Cloud, AWS Lambda, and Vercel [guides](https://github.com/prisma/prisma-examples/tree/master/deployment-platforms), I think it'd be great if there was a guide on how to deploy your Prisma project to Digital Ocean. I recall an old Prisma 1 guide on how to deploy to a Droplet so something like that, updated for Prisma 2, would be great. I know many people use Digital Ocean's managed databases along with a Droplet so covering that would be nice.

Thanks, and congratulations again on the 2.0 release.

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale. 

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
