### ISSUE TITLE
Add Dockerfile example(s)

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma-examples#1856]
It was removed at some point see https://github.com/prisma/prisma-examples/issues/1437

**Comment by Jolg42** [comment]
Example from nestjs-prisma:

Dockerfile
https://github.com/marcjulian/nestjs-prisma/blob/master/src/nestjs-prisma/templates/docker/Dockerfile

docker-compose.yml
https://github.com/marcjulian/nestjs-prisma/blob/master/src/nestjs-prisma/templates/docker/docker-compose.yml

**Comment by marcjulian** [comment]
Files have moved

https://github.com/notiz-dev/nestjs-prisma/tree/main/schematics/nestjs-prisma/templates/docker

Dockerfile
https://github.com/notiz-dev/nestjs-prisma/blob/main/schematics/nestjs-prisma/templates/docker/common/Dockerfile

**Comment by TMInnovations** [comment]
Have the files moved again? I only get 404 ;-)

**Comment by marcjulian** [comment]
@TMInnovations yes they moved again! Repo moved and also added docker-compose.yml for postgres and mysql.
I updated the links.

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
