### ISSUE TITLE
Update all example schemas to use natural order of fields

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-examples#1954]
For example:
ID first, then scalar fields and last relation scalar fields.

Right now: 
Pretty random.

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
