### ISSUE TITLE
[Tests] Undo ignoring Nexus Schema projects after changes to Nexus Schema

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-examples#1992]
Undo https://github.com/prisma/prisma-examples/commit/a84fa03fa9a51f1dca525f36a87c8dbbfa09c02e so all projects are properly tested again.

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
