### ISSUE TITLE
Replace references to specs repo

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-examples#2007]
For example https://github.com/prisma/prisma-examples/blob/496ab21dc28ae13dc3bcb2494c664a92fa4a2668/.github/readmes/deployment-platforms/_setup-2-swap.md#L10

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
