### ISSUE TITLE
GraphQLServer schema type is wrong in graphql-typegraphql example

### ISSUE THREAD

**Issue by redbaron76** [prisma/prisma-examples#2165]
Trying to follow the `typescript/graphql-typegraphql` example, the schema type produced by the typescript-graphql `buildSchema` is not accepted by the graphql-yoga `schema` prop in the server constructor.

I had to workaround it by setting an assumption `as any` to suppress the error as follows:

```
import 'reflect-metadata'
import * as tq from 'type-graphql'
import { PostResolver } from './PostResolver'
import { UserResolver } from './UserResolver'
import { GraphQLServer } from 'graphql-yoga'
import { createContext } from './context'

const app = async () => {
  const schema = await tq.buildSchema({
    resolvers: [PostResolver, UserResolver],
  }) as any;

  const context = createContext()

  new GraphQLServer({ schema, context }).start(() =>
    console.log(
      `🚀 Server ready at: http://localhost:4000\n⭐️  See sample queries: http://pris.ly/e/ts/graphql-typegraphql#using-the-graphql-api`,
    ),
  )
}

app()
```

Any idea about how to fix it?
Thanks

**Comment by nikolasburk** [comment]
Hey @redbaron76, thanks a lot for opening this issue! The problem came from a type inconsistency between TypeGraphQL and graphql-yoga. grapql-yoga still was expecting an "old" version of the `GraphQLSchema` type, so that's why it failed. I just fixed this by swapping graphql-yoga against apollo-server: https://github.com/prisma/prisma-examples/pull/2228
