### ISSUE TITLE
"TypeError: xs.reduce is not a function" when execute "npm run dev", error at "ts-node --transpile-only src/schema"

### ISSUE THREAD

**Issue by dy-100000** [prisma/prisma-examples#2177]
Hello, 

I followed the installation guide to run the demo, but an error  "TypeError: xs.reduce is not a function" occured when execute "npm run dev" of "typescript/graphql-apollo-server/". 

The error is located at CLI "ts-node --transpile-only src/schema"

It seems the error is at NEXUS level, because I had the same issue in other project.

**Comment by divyenduz** [comment]
Hey, thanks for raising this, yes, it is fixed in `nexus-plugin-prisma` 0.23.0. Closing this issue, please feel free to open a new issue if the problem persists. 

P.S. we fixed example via https://github.com/prisma/prisma-examples/pull/2182 (notice that a `semver` dep needs to be added in `0.23.0`, this may be fixed with a hotfix)
