### ISSUE TITLE
Feed slack message format is sometimes broken

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-examples#2184]
![image](https://user-images.githubusercontent.com/746482/97684235-0029f400-1a99-11eb-99b2-dc6bf629846e.png)

Example link: https://prisma-company.slack.com/archives/CUH6B8FUJ/p1603907960013600

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
