### ISSUE TITLE
Slack messages on each example test and the full workflow failure/start/success

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma-examples#2187]
This should already happen in some capacity via https://github.com/prisma/prisma-examples/pull/2180 https://github.com/prisma/prisma-examples/pull/2111 and https://github.com/prisma/prisma-examples/pull/2100

This issue tracks writing down the slack notification behaviour we actually want and implementing it.

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
