### ISSUE TITLE
What is the difference between these two examples ?

### ISSUE THREAD

**Issue by ahmedosama74574** [prisma/prisma-examples#2370]
https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql

https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql-apollo-server

They seem exactly the same. Is there any difference ?

**Comment by nikolasburk** [comment]
Hey @ahmedosama74574, thanks for pointing this out! To briefly answer your question: There's indeed no difference between these two examples any more (the `graphql` example used to use `graphql-yoga` instead of `apollo-server` but since we migrate it to `apollo-server` recently the examples are now practically the same). I'll leave this issue open until one of the two is removed 👍

**Comment by nikolasburk** [comment]
This is now resolved, however the `graphql-apollo-server` directory still exists so that the link doesn't 404 for people who find it in the wild 🙂 

![image](https://user-images.githubusercontent.com/4058327/108999124-273caf00-76a2-11eb-9457-aa1ff70593ed.png)
