### ISSUE TITLE
Green question on schema entry

### ISSUE THREAD

**Issue by jdevng** [prisma/prisma-examples#2387]
Why is the database used as the schema entry in the examples - I would assume as a new user that using prisma migrate might be easier, and then generating the client from there. What am I missing?

**Comment by nikolasburk** [comment]
Hey @jdevng, thanks a lot for raising this! The main reason why we have not been using Prisma Migrate in the examples was because it has been in an experimental state until ~1 month ago. We didn't want people to get started with an experimental tool when they learn about Prisma.

However, since [Prisma Migrate is now in Preview](https://www.prisma.io/blog/prisma-migrate-preview-b5eno5g08d0b) and the production-ready launch is coming closer, we are indeed planning to adjust the setup flow of the examples.

I'll leave this issue open until we have made that change (might still take a few weeks since we are also planning a few bigger changes to the repo in general).

**Comment by jdevng** [comment]
good info. One of the reasons I'm asking is that i actually don't see the prisma db making it to the resolver functions, so i started questioning everything. Feel free to close out. I can't tell you guys how much these examples help out in the basic understanding.

**Comment by nikolasburk** [comment]
Most of the examples have been updated to use Migrate, so I'm closing this issue 🙂
