### ISSUE TITLE
Move folder exclusion from test execution to matrix generation

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-examples#3022]
Currently we exclude some folder in the repo from running tests:
https://github.com/prisma/prisma-examples/blob/cb99c8c51c710a5b500229b6de385eb81befddd3/.github/scripts/test-all.sh#L18

That leads to problems and confusion like this:
https://github.com/prisma/prisma-examples/pull/3020#pullrequestreview-705687840
![image](https://user-images.githubusercontent.com/183673/125769293-5b24d962-d99a-47d3-a59d-3eb4bcd941f0.png)
Looks like we are testing something, but we are really not.

So instead of skipping just running the tests, we could/should skip scheduling them:
https://github.com/prisma/prisma-examples/blob/cb99c8c51c710a5b500229b6de385eb81befddd3/.github/workflows/test.yaml#L17-L38

The logic behind that lives in this file:
https://github.com/prisma/prisma-examples/blob/cb99c8c51c710a5b500229b6de385eb81befddd3/.github/scripts/get-packages.js

And it seems as it might be as simple as removing the `databases` folder from the allow list.

One possible problem: There is no automated way that makes sure there _are_ passing tests for the `databases` subfolders.

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
