### ISSUE TITLE
rest-nextjs-api-routes-auth documentation 

### ISSUE THREAD

**Issue by brandoncroberts** [prisma/prisma-examples#3084]
EXAMPLE: prisma-examples/typescript/rest-nextjs-api-routes-auth/

If you use Github OAuth for the authentication, I was getting a 500 'Internal Server Error' and it took me some time and debugging to find the issue. 
The issue was  that if you use Github OAuth, you still need to have an email address associated w/ the User, otherwise the error will be thrown. The email doesn't get set w/ Github OAuth. 

Other than that, great technology! Thanks!

**Comment by ruheni** [comment]
Thanks for the feedback. We'll update the READMEs 🙂

**Comment by brandoncroberts** [comment]
cool thanks!

**Comment by ruheni** [comment]
I'll keep this open until it's updated :)

**Comment by justiny** [comment]
> EXAMPLE: prisma-examples/typescript/rest-nextjs-api-routes-auth/
> 
> If you use Github OAuth for the authentication, I was getting a 500 'Internal Server Error' and it took me some time and debugging to find the issue.
> The issue was that if you use Github OAuth, you still need to have an email address associated w/ the User, otherwise the error will be thrown. The email doesn't get set w/ Github OAuth.
> 
> Other than that, great technology! Thanks!

Running into the same issue.  Do you have an example of how you resolved it?  Thanks!

**Comment by ruheni** [comment]
You'll need to disable privacy settings if you'd like your user email returned according to the [NextAuth docs](https://next-auth.js.org/v3/providers/github#example).

I'll add the note in the example's docs.

![image](https://user-images.githubusercontent.com/33921841/143032020-047d29da-f1ec-41ff-997c-e8710ae8333b.png)
 
 NextAuth v4 is still in beta but will include an email by default.
 
 In the meantime, here's a workaround you can use to return the email. You can add it to the callback. 
 ```typescript
  callbacks: {
    signIn: async (profile, account, metadata) => {
      // https://developer.github.com/v3/users/emails/#list-email-addresses-for-the-authenticated-user
      const res = await fetch('https://api.github.com/user/emails', {
        headers: {
          'Authorization': `token ${account.accessToken}`
        }
      })
      const emails = await res.json()
      if (!emails || emails.length === 0) {
        return
      }
      // Sort by primary email - the user may have several emails, but only one of them will be primary
      const sortedEmails = emails.sort((a, b) => b.primary - a.primary)
      profile.email = sortedEmails[0].email
    },
  },

```
 Since fetch runs on the server, you have to use a Node.js implementation, for example `node-fetch`.

 From: https://github.com/nextauthjs/next-auth/issues/374#issuecomment-659083083
 
 I'll update the example to return the email when working with NextAuth v3 and remove the block once v4 is out of beta.
