### ISSUE TITLE
Example with different approaches for error handling

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-examples#321]
There [has been some discussion](https://github.com/graphcool/prisma/issues/1738) about how to throw errors from resolvers properly.

An example that show cases different approaches that are considered best practice would be super helpful!

If anyone's interested in contributing such an example, feel free to ping me [in Slack](http://slack.graph.cool) (my handle there is @nilan), happy to collaborate on this one! 🙌

**Comment by Jaikant** [comment]
I used ApolloError and 
`const { ApolloError } = require('apollo-server-errors')
throw new ApolloError(MSG, CODE)
`
and it worked well.

`apollo-error` otoh, doesn't implement the latest spec (uses `data` property instead of `extensions`)

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale. 

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
