### ISSUE TITLE
AWS SAM prisma lambda layer example

### ISSUE THREAD

**Issue by richardwardza** [prisma/prisma-examples#3840]
Hi all and @nikolasburk ,

I know there is an [AWS serverless lambda Prisma example](https://github.com/prisma/prisma-examples/tree/latest/deployment-platforms/aws-lambda) but nothing yet for using AWS SAM with Prisma as a Lambda Layer.

I've been working on an example of [a lambda using a Prisma layer](https://github.com/richardwardza/prisma-lambda-layers) and being deployed with AWS SAM but it still needs some cleaning up.

I'm happy to use one of the existing graphql examples ([possibly this one](https://github.com/prisma/prisma-examples/tree/latest/typescript/graphql)), put it into a lamdba and have Prisma in it's own layer.

Would this be of interest?

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏

**Comment by zachuri** [comment]
Hi!

I know this is closed but if anyone comes across this I think this repo could be helpful: 

https://github.com/codeanding/prisma-lambda-layer
