### ISSUE TITLE
serverless aws-nodejs-typescript with lambda layers example

### ISSUE THREAD

**Issue by kaykhan** [prisma/prisma-examples#4085]
I'm hoping i could get some help with getting prisma to work via a lambda layer with serverless typescript template. https://www.serverless.com/framework/docs/providers/aws/cli-reference/create

The template can be bootstraped using the following command - `serverless create --template aws-nodejs-typescript --path myService` 

The usecase behind this been outlined here - https://dev.to/sabinthedev/managing-lambda-size-with-multiple-prisma-clients-4m8l - the difference is the example does not use the typescript template.

I believe there are some packaging difference between the example in the blog above by `sabinthedev` and the `aws-nodejs-typescript` template. Ultimately the error i am receiving is

```
✖ Error: ENOENT: no such file or directory, open '/home/app1/.esbuild/.build/schema.prisma'
```

You can find a minimal reproduction of this here - https://github.com/kaykhan/prisma-typescript-example

**Comment by hayder-nearsure** [comment]
I'm getting the same error

**Comment by noecende** [comment]
Were you able to solve it? I'm getting the same error.

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
