### ISSUE TITLE
Need a data type and query option for geo location

### ISSUE THREAD

**Issue by ShourovRoy** [prisma/prisma-examples#4220]
Need a data type and query option for geo location

**Comment by jeky1950** [comment]
What about this
```prisma
model User {
    id String @default(cuid())
    current_geolocation Json?
    location_last_updated_at DateTime @updatedAt
}
```

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
