### ISSUE TITLE
[Idea] E2E using test containers

### ISSUE THREAD

**Issue by yangricardo** [prisma/prisma-examples#4505]
Hi,
I have worked with several frameworks and tecnologies.
Even with some new experiences with software development testing, there are some tools that i already see value,
like TestContainers, that i had a brief view in a Spring Boot (Java) development.
Would be nice to have an example of using Prisma ORM and TestContainers, since it offers ways to also be used in NodeJS ecosystem.

https://github.com/testcontainers/testcontainers-node
https://www.testcontainers.org

**Comment by jharrell** [comment]
Hello!

We are reviewing our old pull requests and issues in this repo. In the case that there hasn't been much activity or work, we're going to close them as stale.

We'd still love your contribution, however! If you think that this issue is still relevant, please feel free to comment here or open a new issue. Thank you! 🙏
