### ISSUE TITLE
ctx and Prisma instance question

### ISSUE THREAD

**Issue by brikou** [prisma/prisma-examples#8]
Hi great repo, 1.17 looks fantastic!

I have a real question: why do you attach prisma to context instead of doing a regular import of the instance?

**Comment by timsuchanek** [comment]
@brikou the reason is, that when you want to use the Dataloader with full Cache later, you don't need to change your code. So this basically means, that on each request, a new Client instance is created. It's not used right now, but will later help to enable caching on a request basis.

Does this answer your question?

**Comment by abhiaiyer91** [comment]
The intention of this to establish patterns we think will help for working with prisma. By attaching the Prisma to context we establish a pattern for your code that can take advantage of caching once we enable that feature. That way when we release it people can take advantage of it for free. 

By all means though import Prisma in your own files if it makes sense for you

**Comment by brikou** [comment]
Thanks @abhiaiyer91, can't wait to see the cache feature coming
